modified for 40 and added display

diff --git a/.github/workflows/main-serverless-service.yml b/.github/workflows/main-serverless-service.yml
--- a/.github/workflows/main-serverless-service.yml
+++ b/.github/workflows/main-serverless-service.yml
@@ -37,16 +37,23 @@ jobs:
       run: |
         coverage="${{ steps.coverage.outputs.coverage }}"
         if [[ "$coverage" =~ ^[0-9]*$ ]]; then
-          if [ -n "$coverage" ] && [ "$coverage" -ge 40 ]; then
-            echo "Coverage is greater than or equal to 40%. Proceeding..."
+          if [ -n "$coverage" ]; then
+            echo "Coverage is $coverage%. Proceeding..."
+            if [ "$coverage" -ge 40 ]; then
+              echo "Coverage is greater than or equal to 40%. Proceeding..."
+            else
+              echo "Coverage is less than 40%. Exiting..."
+              exit 1  # Exit with an error code to stop the workflow
+            fi
           else
-            echo "Coverage is less than 40%. Exiting..."
+            echo "Coverage value is empty. Exiting..."
             exit 1  # Exit with an error code to stop the workflow
           fi
         else
-          echo "Invalid coverage value. Exiting..."
+          echo "Invalid coverage value: $coverage. Exiting..."
           exit 1  # Exit with an error code to stop the workflow
         fi
+    
     
 
     - name: Set up AWS credentials
